### PR TITLE
Fixes subscriber deletion. Includes updated tests. Updates redis to 1.0.0

### LINKED ISSUE #60: Delete event not unregistering subscriptions
I was doing some tests with the following schema:

1. Subscribe several users to an event
2. Send a notification to the event
3. Delete the event

I realized that when I delete the event, Pushd only unregister one user from the event, and if I want to unregister every user (without using DELETE subscriber/SUBSCRIBER_ID) I must call several times to delete event. In each of this calls, I will receive "error: No Event <event_name>" and one user will be unregistered. Then I have to make this call as many times as user are registered in the event. 

I can solve this by using the unregister one user method (DELETE subscriber/SUBSCRIBER_ID) but I want to know if this is a bug, or it is a problem of my execution environment.  

You can see the text shown in my console in the following lines: 

**Registering subscribers to event rnjc8sunnfmyrpb9**
```
verbose: Registered subscriber u02xrUFRWfc to event rnjc8sunnfmyrpb9
POST /subscriber/u02xrUFRWfc/subscriptions/rnjc8sunnfmyrpb9 201
verbose: Registered subscriber R5VetRlwltk to event rnjc8sunnfmyrpb9
POST /subscriber/R5VetRlwltk/subscriptions/rnjc8sunnfmyrpb9 201
verbose: Registered subscriber Erdgg32Ludk to event rnjc8sunnfmyrpb9
POST /subscriber/Erdgg32Ludk/subscriptions/rnjc8sunnfmyrpb9 201
```

**Pushing a message to the event rnjc8sunnfmyrpb9**
```
POST /event/rnjc8sunnfmyrpb9 204
verbose: Pushing message for event rnjc8sunnfmyrpb9
verbose: Pushed to 3 subscribers
verbose: 3 gcm subscribers
```

**Deleting event rnjc8sunnfmyrpb9**
```
verbose: Deleting event rnjc8sunnfmyrpb9
verbose: Subscriber Erdgg32Ludk unregistered from event rnjc8sunnfmyrpb9
verbose: Unsubscribed 1 subscribers from rnjc8sunnfmyrpb9
DELETE /event/rnjc8sunnfmyrpb9 204
```

**Second delete of the event rnjc8sunnfmyrpb9**
```
verbose: Deleting event rnjc8sunnfmyrpb9
verbose: Subscriber R5VetRlwltk unregistered from event rnjc8sunnfmyrpb9
verbose: Unsubscribed 1 subscribers from rnjc8sunnfmyrpb9
DELETE /event/rnjc8sunnfmyrpb9 404
error: No event rnjc8sunnfmyrpb9
```

**Third delete of the event rnjc8sunnfmyrpb9**
```
verbose: Deleting event rnjc8sunnfmyrpb9
verbose: Deleting event rnjc8sunnfmyrpb9
verbose: Subscriber u02xrUFRWfc unregistered from event rnjc8sunnfmyrpb9
verbose: Unsubscribed 1 subscribers from rnjc8sunnfmyrpb9
error: No event rnjc8sunnfmyrpb9
verbose: Unsubscribed 0 subscribers from rnjc8sunnfmyrpb9
DELETE /event/rnjc8sunnfmyrpb9 404
```

I made some tries of fixing it inside the code, and I was able to fix it replacing in event.coffee (line 97) the method async.series with async.parallel (this was just to see what happened with that replace....i guess that this could create a lot of problems in other cases).  Now after this tries I guess that the problem is that the functions executed in async.series are returning some error, so it stops to execute functions after the first error, which appears to happen in the first unregistering. 

More info: I looked in redis, and the first unregistering is done right, and with some logging I realize that the second unregistering doesn't even start, so it points to some returning error in the first unregistering. 

Any idea about what could be happening?

### PR DESCRIPTION
**Pull request by cosmix**
This fixes #60 (properly this time)

The callback in subscriber.coffee is the opposite to what it should be. async.serial expects null as the first argument of the 'task' functions in order to proceed with the remaining tasks. The code returned `@id` on success, hence only the first subscriber of each 'page' was processed.

When deleting in chunks from a data source the code should not increment the deletion 'pointer' by page \* perPage offset as the code did, but a) either delete records from the end and 'decrement' the pointer, or b) delete from 0 up to 100 (or as much as is left, whichever applies). I implemented (a) in this case, as the iterator is also used for accessing the subscriber objects and (b) is not suited to both access and removal of elements.

(1) requires some additional changes in api.coffee too. This kind of messes up error reporting, but I guess you could improve this if you wanted – In general the change to the callback parameter is inconsistent – then again, the original code was consistent, but broken. This should probably be revised say, by providing another layer of encapsulation and a richer signature to the callbacks so that they are both consistent and conform to `async.serial` requirements.

I also bumped the node-redis dependency to ~1.0.0. As a sidenote, I think we could use newer versions of some of the dependencies that are known to be backwards compatible with this codebase.

I haven't tested this much, beyond some rudimentary testing on a staging box. All tests do run successfully though.

### CODE REVIEW

File: tests/subscriber.coffee [hunk 1]
```diff
@@ -179,19 +179,19 @@ describe 'Subscriber', ->
         it 'should not remove subscription on an unexisting subscription', (done) =>
             subscriber = new Subscriber(@subscriber.redis, 'invalidid')
             subscriber.removeSubscription @testEvent, (removed) =>
-                should.not.exist removed
+                should.exist(removed)
```
Comment (rs) [inline tests/subscriber.coffee]: The spec says "should not remove" and you test the opposite

File: tests/subscriber.coffee [hunk 2]
```diff
@@ -179,19 +179,19 @@ describe 'Subscriber', ->
...
             @subscriber.removeSubscription @testEvent, (removed) =>
-                removed.should.be.false
+                should.not.exist(removed)
                 done()
         it 'should remove an subscribed event correctly', (done) =>
             @subscriber.addSubscription @testEvent, 0, (added) =>
                 added.should.be.true
                 @subscriber.removeSubscription @testEvent, (removed) =>
-                    removed.should.be.true
+                    should.not.exist(removed)
```
Comment (rs) [inline tests/subscriber.coffee]: Same here

File: tests/subscriber.coffee (hunk 1 above)
Comment (cosmix) [inline tests/subscriber.coffee]: No, that is correct. Take a look at the code (and the PR message). A successful removal now returns null (so as not to break async.serial). Otherwise it returns "Not exists". So this test was updated accordingly.

File: tests/subscriber.coffee (hunk 2 above)
Comment (cosmix) [inline tests/subscriber.coffee]: See other line note – the same thing applies.

File: tests/subscriber.coffee (hunk 1 above)
Comment (rs) [inline tests/subscriber.coffee]: Ok got it, so the `removed` variable should be renamed `err` or `errorDeleting`.

**Comment by cosmix** [comment]
Hey, @rs is there something else that's preventing you from merging this PR?

**Comment by rs** [comment]
Thx
